from __future__ import annotations

import json
from pathlib import Path

from verilogic_ns_api.baselines.configuration import repository_root
from verilogic_ns_api.main import create_app
from verilogic_ns_api.orchestration.models import (
    ApiErrorResponse,
    CapabilitiesResponse,
    PipelineRequest,
    PipelineResult,
    PipelineRunAccepted,
    PipelineRunState,
)
from verilogic_ns_api.reasoning.models import sha256_payload

SCHEMAS: dict[str, type] = {
    "neurosymbolic-run-request.v1.schema.json": PipelineRequest,
    "neurosymbolic-run-accepted.v1.schema.json": PipelineRunAccepted,
    "neurosymbolic-run-state.v1.schema.json": PipelineRunState,
    "neurosymbolic-pipeline-result.v1.schema.json": PipelineResult,
    "neurosymbolic-capabilities.v1.schema.json": CapabilitiesResponse,
    "neurosymbolic-api-error.v1.schema.json": ApiErrorResponse,
}


def contract_schema_hashes() -> dict[str, str]:
    return {
        name.removesuffix(".v1.schema.json"): sha256_payload(model.model_json_schema())
        for name, model in SCHEMAS.items()
    }


def export_contracts(*, root: Path | None = None, check: bool = False) -> list[Path]:
    resolved = repository_root(root or Path.cwd())
    expected: dict[Path, str] = {}
    for name, model in SCHEMAS.items():
        expected[resolved / "schemas" / name] = _json(model.model_json_schema())
    expected[resolved / "schemas" / "openapi.v1.json"] = _json(create_app().openapi())
    expected[resolved / "frontend" / "src" / "lib" / "neurosymbolic-contract.generated.ts"] = (
        _typescript_contract()
    )

    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if check:
        if stale:
            names = ", ".join(path.name for path in stale)
            raise RuntimeError(f"generated API contracts are stale: {names}")
        return []
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return sorted(expected)


def _json(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _typescript_contract() -> str:
    hashes = json.dumps(contract_schema_hashes(), indent=2, sort_keys=True)
    return f"""// Generated by `python -m verilogic_ns_api.orchestration export-schemas`.
// Do not edit by hand.

export const INPUT_MODES = ["NATURAL_LANGUAGE", "FORMAL_AST"] as const;
export const POLICY_MODES = ["P0_RAW", "P1_CORRECTED", "P2_SELECTIVE"] as const;
export const RUN_STATUSES = ["QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCEL_REQUESTED", "CANCELLED"] as const;
export const PIPELINE_DISPOSITIONS = ["ANSWERED", "ABSTAINED", "ERROR"] as const;
export const LOGICAL_RESULTS = ["ENTAILED", "CONTRADICTED", "UNKNOWN", "INCONSISTENT"] as const;
export const STAGE_NAMES = ["INPUT_VALIDATION", "THEORY_PARSING", "QUERY_PARSING", "SOURCE_COVERAGE", "SEMANTIC_VALIDATION", "CRITIC", "CORRECTION", "RELIABILITY_POLICY", "SYMBOLIC_REASONING", "PROOF_VERIFICATION", "FINAL_DECISION"] as const;
export const STAGE_STATUSES = ["NOT_STARTED", "RUNNING", "SUCCEEDED", "SKIPPED", "ABSTAINED", "FAILED"] as const;

export type InputMode = (typeof INPUT_MODES)[number];
export type PolicyMode = (typeof POLICY_MODES)[number];
export type RunStatus = (typeof RUN_STATUSES)[number];
export type PipelineDisposition = (typeof PIPELINE_DISPOSITIONS)[number];
export type LogicalResult = (typeof LOGICAL_RESULTS)[number];
export type StageName = (typeof STAGE_NAMES)[number];
export type StageStatus = (typeof STAGE_STATUSES)[number];

export interface NaturalLanguageStatement {{
  source_id?: string | null;
  kind: "fact" | "rule";
  text: string;
}}

export interface PipelineRequest {{
  schema_version: "1.0";
  input_mode: InputMode;
  policy_mode: PolicyMode;
  natural_language?: {{ statements: NaturalLanguageStatement[]; query: string }} | null;
  formal_ast?: {{ theory: Record<string, unknown>; query: Record<string, unknown> }} | null;
}}

export interface StageTrace {{
  stage: StageName;
  status: StageStatus;
  duration_ms: number;
  cache_status: "hit" | "miss" | "mixed" | "not_applicable";
  error_code?: string | null;
  message?: string | null;
}}

export interface ExplanationStep {{
  sequence: number;
  kind: "fact" | "rule";
  statement: string;
  source_id: string;
  source_text: string;
  depth: number;
  node_id: string;
}}

export interface PipelineResult {{
  schema_version: "1.0";
  disposition: PipelineDisposition;
  logical_result?: LogicalResult | null;
  explanation: {{
    schema_version: "1.0";
    headline: string;
    summary: string;
    steps: ExplanationStep[];
    support_root_id?: string | null;
    opposition_root_id?: string | null;
    proof_depth?: number | null;
    proof_hash?: string | null;
    verifier_status: "VERIFIED" | "NOT_APPLICABLE";
    reasons: string[];
  }};
  trace: StageTrace[];
  provenance: Record<string, unknown>;
  proof?: Record<string, unknown> | null;
  proof_verification?: Record<string, unknown> | null;
  reasoning_telemetry?: Record<string, unknown> | null;
  accepted_theory?: Record<string, unknown> | null;
  correction_attempted: boolean;
  abstention_reason?: string | null;
  error?: {{ stage: StageName; code: string; message: string }} | null;
}}

export interface PipelineRunAccepted {{
  schema_version: "1.0";
  run_id: string;
  status: "QUEUED" | "RUNNING";
}}

export interface PipelineRunState {{
  schema_version: "1.0";
  run_id: string;
  status: RunStatus;
  current_stage?: StageName | null;
  submitted_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  result?: PipelineResult | null;
}}

export interface CapabilitiesResponse {{
  schema_version: "1.0";
  api_version: "v1";
  supported_input_modes: InputMode[];
  supported_policy_modes: PolicyMode[];
  symbolic_engine_ready: boolean;
  local_model_ready: boolean;
  provider_mode: "live" | "cache_only";
  model_name: string;
  model_digest: string;
  provider_version: string;
  maximum_active_jobs: 1;
  maximum_queued_jobs: number;
  resource_limits: Record<string, number | null>;
  schema_hashes: Record<string, string>;
}}

export const CONTRACT_SCHEMA_HASHES = {hashes} as const;
"""
