from __future__ import annotations

import json
from pathlib import Path

from verilogic_ns_api.baselines.configuration import repository_root
from verilogic_ns_api.research_frontend.models import (
    AggregateExportManifest,
    ComparisonCompatibility,
    ExperimentDetail,
    ExperimentSummary,
    MetricEvidence,
    NormalizedAstInspection,
    ResearchApiError,
    ResearchCatalogue,
    sha256_json,
)

SCHEMAS: dict[str, type] = {
    "research-catalogue.v1.schema.json": ResearchCatalogue,
    "research-experiment-summary.v1.schema.json": ExperimentSummary,
    "research-metric-evidence.v1.schema.json": MetricEvidence,
    "research-comparison-compatibility.v1.schema.json": ComparisonCompatibility,
    "research-experiment-detail.v1.schema.json": ExperimentDetail,
    "research-normalized-ast-inspection.v1.schema.json": NormalizedAstInspection,
    "research-aggregate-export-manifest.v1.schema.json": AggregateExportManifest,
    "research-api-error.v1.schema.json": ResearchApiError,
}


def schema_hashes() -> dict[str, str]:
    return {
        name.removesuffix(".v1.schema.json"): sha256_json(model.model_json_schema())
        for name, model in SCHEMAS.items()
    }


def export_schemas(*, root: Path | None = None, check: bool = False) -> list[Path]:
    resolved = repository_root(root or Path.cwd())
    expected: dict[Path, str] = {
        resolved / "schemas" / name: _json(model.model_json_schema())
        for name, model in SCHEMAS.items()
    }
    expected[resolved / "frontend" / "src" / "lib" / "research-contract.generated.ts"] = (
        _typescript_contract()
    )
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if check:
        if stale:
            raise RuntimeError(
                "generated research contracts are stale: " + ", ".join(path.name for path in stale)
            )
        return []
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return sorted(expected)


def _json(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _typescript_contract() -> str:
    hashes = json.dumps(schema_hashes(), indent=2, sort_keys=True)
    return f"""// Generated by `python -m verilogic_ns_api.research_frontend export-schemas`.
// Do not edit by hand.

export const EXPERIMENT_STATUSES = ["PASS", "BLOCKED", "INVALIDATED", "COMPLETE_WITH_NEGATIVE_RESULT"] as const;
export const COMPARISON_TYPES = ["PAIRED", "SAME_SELECTION_DIFFERENT_REPRESENTATION", "DESCRIPTIVE_ONLY", "INCOMPARABLE"] as const;
export const EVIDENCE_TYPES = ["DIRECTLY_OBSERVED", "DERIVED", "DOCUMENTED", "UNAVAILABLE"] as const;
export type ExperimentStatus = (typeof EXPERIMENT_STATUSES)[number];
export type ComparisonType = (typeof COMPARISON_TYPES)[number];
export type EvidenceType = (typeof EVIDENCE_TYPES)[number];

export interface MetricEvidence {{
  metric_id: string; display_name: string; value: number | null; unit: string;
  numerator: number | null; denominator: number | null; sample_size: number;
  dataset: string; dataset_version: string; split: string; benchmark_variant: string;
  selection_manifest: string | null; phase: string; condition: string; policy_mode: string | null;
  model_name: string | null; model_digest: string | null; run_id: string | null;
  evidence_type: EvidenceType; source_artifact: string; source_artifact_hash: string;
  source_commit: string | null; derivation_formula: string | null; comparability_group: string;
  limitations: string[]; verification_status: string; dimensions: Record<string, string>;
}}
export interface ExperimentSummary {{
  experiment_id: string; name: string; phase: string; condition: string;
  policy_mode: string | null; status: ExperimentStatus; recorded_at: string | null;
  commit: string | null; model_name: string | null; dataset: string; split: string;
  sample_size: number; replay_status: string; provider_call_count: number | null;
  api_cost_usd: number | null; primary_metrics: Record<string, number | null>;
  main_limitation: string | null; comparability_groups: string[]; chart_eligible: boolean;
  evidence_verification_status: string;
}}
export interface CatalogueOverview {{
  schema_version: "1.0"; catalogue_id: string; catalogue_version: string;
  catalogue_hash: string; evidence_validation_status: "VERIFIED";
  experiment_count: number; comparison_count: number; experiments: ExperimentSummary[];
  global_limitations: string[]; zero_cost: boolean; provider_calls_during_phase8: number;
}}
export interface ExperimentDetail extends Omit<ExperimentSummary, "primary_metrics" | "main_limitation"> {{
  branch: string | null; model_digest: string | null; dataset_version: string;
  benchmark_variant: string; selection_manifest: string | null; run_id: string | null;
  metrics: MetricEvidence[]; evidence_sources: string[]; limitations: string[];
}}
export interface ComparisonCompatibility {{
  comparison_id: string; title: string; comparison_type: ComparisonType;
  experiment_ids: string[]; paired: boolean; same_selection: boolean;
  supported_metrics: string[]; outcome_counts: Record<string, number | null>;
  warning: string; evidence_sources: string[]; limitations: string[];
}}
export interface ExperimentListResponse {{
  schema_version: "1.0"; items: ExperimentSummary[]; total: number; page: number; page_size: number;
}}
export interface AstLiteral {{
  canonical_id: string; predicate: string; arguments: Array<{{kind: "entity" | "variable"; value: string}}>;
  negated: boolean; source_id: string; display: string;
}}
export interface AstRule {{
  rule_id: string; variables: string[]; premises: AstLiteral[]; conclusion: AstLiteral; source_id: string;
}}
export interface AstSourceMapping {{
  source_id: string; text: string; referenced_by: string[];
}}
export interface NormalizedAstInspection {{
  schema_version: "1.0"; theory_id: string; canonical_theory_id: string;
  facts: AstLiteral[]; rules: AstRule[]; query: AstLiteral;
  predicates: Array<{{name: string; arity: 1 | 2; argument_types: string[] | null}}>;
  entities: Array<Record<string, string | null>>; source_mapping: AstSourceMapping[];
  semantic_validation_status: "VALID"; source_coverage_status: "COMPLETE" | "INCOMPLETE";
  correction_attempted: boolean; correction_diff: Record<string, unknown>;
  proof_roots: string[]; canonical_json: Record<string, unknown>;
}}
export const RESEARCH_SCHEMA_HASHES = {hashes} as const;
"""
