from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from verilogic_ns_api.research_frontend.models import (
    ComparisonCompatibility,
    ComparisonType,
    EvidenceType,
    EvidenceVerification,
    ExperimentDetail,
    ExperimentStatus,
    MetricEvidence,
    ResearchCatalogue,
    SourceArtifact,
)

CHECKPOINT = "7ffffed4ae9dc1274b8f4fecd26531a7be665103"
PILOT_MANIFEST = "experiments/manifests/proofwriter-owa-depth5-dev-pilot.v1.json"
MODEL = "qwen3.5:4b-q4_K_M"
MODEL_DIGEST = "2a654d98e6fba55d452b7043684e9b57a947e393bbffa62485a7aac05ee4eefd"
DATASET = "ProofWriter"
DATASET_VERSION = "V2020.12.3"
DEV = "development"
VARIANT = "OWA depth-5 balanced development pilot"

SOURCES: dict[str, SourceArtifact] = {
    "phase5-results": SourceArtifact(
        artifact_id="phase5-results",
        path="docs/PHASE5_PILOT_RESULTS.md",
        sha256="bf89e8c9c89bd045dcd7c9cc9aa737d09bb6348208114e424da4fd5c419c27cf",
        source_commit="bd9faaef321fb7e926c77d1678517eb9f65b555b",
        tracked=True,
        description="Sanitized Phase 3 comparison and Phase 5 parser-pilot results.",
    ),
    "symbolic-engine": SourceArtifact(
        artifact_id="symbolic-engine",
        path="docs/SYMBOLIC_ENGINE.md",
        sha256="95b4dc554081e9ee125ab13e14aa38bf14512c3ef87fc488f9100c8a29d5fdbe",
        source_commit="eb319d661eca3ae1164407806a91c80eb2510a9e",
        tracked=True,
        description="Phase 4 deterministic reasoner and oracle-structure conformance report.",
    ),
    "phase6-original": SourceArtifact(
        artifact_id="phase6-original",
        path="docs/PHASE6_PILOT_RESULTS.md",
        sha256="16654dac532310773cac188e49f743edff56979b6e3c188bf59c55c7ce9dd7f7",
        source_commit="4270c83e2d5618939de9120bde307df966ce6ae3",
        tracked=True,
        description="Blocked original Phase 6 recovery report.",
    ),
    "phase6-r2": SourceArtifact(
        artifact_id="phase6-r2",
        path="docs/PHASE6_RECOVERY_R2_RESULTS.md",
        sha256="9266855183e29e1011fe3298bef01f8b44b2efe8733fa05acf3d5c00c11a56a2",
        source_commit="3c6106d21288ed31829bd6eeb5db96e7d9ee9705",
        tracked=True,
        description="Blocked Phase 6-R2 terminal structured-output report.",
    ),
    "phase6-r3": SourceArtifact(
        artifact_id="phase6-r3",
        path="docs/PHASE6_R3_RESULTS.md",
        sha256="7330240f26cff22b370280f5760137e376151c91a2d81ca9b04e6a579c3ede33",
        source_commit="4a74aa56f4b03b4c639b3cf79c74e59ad1e2f7f0",
        tracked=True,
        description="Completed Phase 6-R3 aggregate results and strict replay fingerprints.",
    ),
    "phase7-results": SourceArtifact(
        artifact_id="phase7-results",
        path="docs/PHASE7_VERIFICATION.md",
        sha256="72ab3117dd1fd3fc977d01461cd5547f3764c619b36d73b5b5820fb50e02fb1c",
        source_commit=CHECKPOINT,
        tracked=True,
        description="Phase 7 formal and natural canary integration verification.",
    ),
    "phase8-specification": SourceArtifact(
        artifact_id="phase8-specification",
        path="user-provided/phase8-evidence-specification",
        sha256="44c612961ae8f511f31631d7c42949bd999cc0bb9f829ddf9b3a3d0a5e94c69b",
        source_commit=None,
        tracked=False,
        description="User-provided Phase 8 evidence assertions; documented, not machine-run evidence.",
    ),
    "pilot-selection": SourceArtifact(
        artifact_id="pilot-selection",
        path=PILOT_MANIFEST,
        sha256="16fd49a90f77aa7b59c1b55a62fa1846638beb7a3c86ea07ff97a685d76360b3",
        source_commit="9cd76a631b6c5c7b75d24910b92ffc4955fd7ebc",
        tracked=True,
        description="Frozen 30-example OWA development selection without raw benchmark text.",
    ),
    "phase7-manifest": SourceArtifact(
        artifact_id="phase7-manifest",
        path="experiments/manifests/phase7-integration-canaries.v1.json",
        sha256="8792461f2a1f72e6489ae9ee881a09195019c62da2b50660d8fba958c0b55d9c",
        source_commit="893f592fb8a620797e8a70937f3a40de8828ea03",
        tracked=True,
        description="Frozen Phase 7 synthetic canary identities and constraints.",
    ),
}


def _metric(
    experiment: dict[str, Any],
    metric_id: str,
    display_name: str,
    value: float | int | None,
    unit: str,
    source_id: str,
    *,
    numerator: float | int | None = None,
    denominator: float | int | None = None,
    evidence_type: EvidenceType = EvidenceType.DOCUMENTED,
    formula: str | None = None,
    limitations: tuple[str, ...] = (),
    dimensions: dict[str, str] | None = None,
) -> MetricEvidence:
    source = SOURCES[source_id]
    verification = (
        EvidenceVerification.UNAVAILABLE
        if evidence_type is EvidenceType.UNAVAILABLE
        else EvidenceVerification.HASH_VERIFIED
        if source.tracked
        else EvidenceVerification.SOURCE_HASH_RECORDED
    )
    return MetricEvidence(
        metric_id=metric_id,
        display_name=display_name,
        value=value,
        unit=unit,
        numerator=numerator,
        denominator=denominator,
        dataset=experiment["dataset"],
        dataset_version=experiment["dataset_version"],
        split=experiment["split"],
        benchmark_variant=experiment["benchmark_variant"],
        sample_size=experiment["sample_size"],
        selection_manifest=experiment["selection_manifest"],
        phase=experiment["phase"],
        condition=experiment["condition"],
        policy_mode=experiment.get("policy_mode"),
        model_name=experiment.get("model_name"),
        model_digest=experiment.get("model_digest"),
        run_id=experiment.get("run_id"),
        source_artifact=source.artifact_id,
        source_artifact_hash=source.sha256,
        source_commit=source.source_commit,
        evidence_type=evidence_type,
        derivation_formula=formula,
        comparability_group=experiment["comparability_groups"][0],
        limitations=limitations,
        verification_status=verification,
        dimensions=dimensions or {},
    )


def _base(
    experiment_id: str,
    name: str,
    phase: str,
    condition: str,
    *,
    status: ExperimentStatus,
    commit: str | None,
    branch: str | None,
    source_ids: tuple[str, ...],
    sample_size: int = 30,
    split: str = DEV,
    dataset: str = DATASET,
    dataset_version: str = DATASET_VERSION,
    variant: str = VARIANT,
    manifest: str | None = PILOT_MANIFEST,
    policy: str | None = None,
    model: str | None = MODEL,
    digest: str | None = MODEL_DIGEST,
    run_id: str | None = None,
    replay: str = "DOCUMENTED",
    provider_calls: int | None = None,
    cost: float | None = 0.0,
    limitations: tuple[str, ...] = (),
    groups: tuple[str, ...] = ("pilot-30-natural",),
    chart_eligible: bool = True,
    recorded_at: datetime | None = None,
) -> dict[str, Any]:
    return {
        "experiment_id": experiment_id,
        "name": name,
        "phase": phase,
        "condition": condition,
        "policy_mode": policy,
        "status": status,
        "recorded_at": recorded_at,
        "branch": branch,
        "commit": commit,
        "model_name": model,
        "model_digest": digest,
        "dataset": dataset,
        "dataset_version": dataset_version,
        "split": split,
        "benchmark_variant": variant,
        "sample_size": sample_size,
        "selection_manifest": manifest,
        "run_id": run_id,
        "replay_status": replay,
        "provider_call_count": provider_calls,
        "api_cost_usd": cost,
        "evidence_sources": source_ids,
        "limitations": limitations,
        "comparability_groups": groups,
        "chart_eligible": chart_eligible,
        "evidence_verification_status": EvidenceVerification.HASH_VERIFIED,
    }


def build_catalogue() -> ResearchCatalogue:
    experiments: list[ExperimentDetail] = []

    direct = _base(
        "phase3-direct",
        "Direct local LLM baseline",
        "Phase 3",
        "Direct",
        status=ExperimentStatus.PASS,
        commit="7eddcacfa97729c73f977af61d31b42d3206bbbb",
        branch="phase/03-llm-baselines",
        source_ids=("phase5-results", "phase8-specification", "pilot-selection"),
        run_id="phase3-direct-local-pilot",
        replay="COMPLETED_ZERO_CALL_REPLAY",
        provider_calls=30,
        limitations=("Small development pilot; no statistical-superiority claim.",),
        recorded_at=datetime(2026, 7, 13, tzinfo=UTC),
    )
    direct["metrics"] = (
        _metric(
            direct,
            "accuracy",
            "Accuracy",
            17 / 30,
            "ratio",
            "phase5-results",
            numerator=17,
            denominator=30,
        ),
        _metric(
            direct,
            "coverage",
            "Coverage",
            1.0,
            "ratio",
            "phase5-results",
            numerator=30,
            denominator=30,
        ),
        _metric(
            direct,
            "answered_only_accuracy",
            "Answered-only accuracy",
            17 / 30,
            "ratio",
            "phase5-results",
            numerator=17,
            denominator=30,
        ),
        _metric(
            direct,
            "macro_f1",
            "Macro F1",
            0.545,
            "ratio",
            "phase8-specification",
            limitations=("Approximate documented value; raw metrics are unavailable.",),
        ),
        _metric(direct, "input_tokens", "Input tokens", 10076, "tokens", "phase8-specification"),
        _metric(direct, "output_tokens", "Output tokens", 333, "tokens", "phase8-specification"),
        _metric(
            direct,
            "inference_seconds",
            "Inference time",
            578,
            "seconds",
            "phase8-specification",
            limitations=("Approximate documented duration.",),
        ),
        _metric(
            direct,
            "errors",
            "Errors and refusals",
            0,
            "count",
            "phase8-specification",
            numerator=0,
            denominator=30,
        ),
        _metric(direct, "api_cost_usd", "API cost", 0.0, "usd", "phase5-results"),
    )
    experiments.append(ExperimentDetail.model_validate(direct))

    few = _base(
        "phase3-few-shot",
        "Fixed six-example few-shot local LLM baseline",
        "Phase 3",
        "Few-shot",
        status=ExperimentStatus.PASS,
        commit="7eddcacfa97729c73f977af61d31b42d3206bbbb",
        branch="phase/03-llm-baselines",
        source_ids=("phase5-results", "phase8-specification", "pilot-selection"),
        run_id="phase3-few-shot-local-pilot",
        replay="COMPLETED_ZERO_CALL_REPLAY",
        provider_calls=30,
        limitations=("Small development pilot; no statistical-superiority claim.",),
        recorded_at=datetime(2026, 7, 13, tzinfo=UTC),
    )
    few["metrics"] = (
        _metric(
            few,
            "accuracy",
            "Accuracy",
            15 / 30,
            "ratio",
            "phase5-results",
            numerator=15,
            denominator=30,
        ),
        _metric(
            few,
            "coverage",
            "Coverage",
            1.0,
            "ratio",
            "phase5-results",
            numerator=30,
            denominator=30,
        ),
        _metric(
            few,
            "answered_only_accuracy",
            "Answered-only accuracy",
            0.5,
            "ratio",
            "phase5-results",
            numerator=15,
            denominator=30,
        ),
        _metric(
            few,
            "macro_f1",
            "Macro F1",
            0.502,
            "ratio",
            "phase8-specification",
            limitations=("Approximate documented value; raw metrics are unavailable.",),
        ),
        _metric(few, "input_tokens", "Input tokens", 50876, "tokens", "phase8-specification"),
        _metric(few, "output_tokens", "Output tokens", 268, "tokens", "phase8-specification"),
        _metric(
            few,
            "inference_seconds",
            "Inference time",
            890,
            "seconds",
            "phase8-specification",
            limitations=("Approximate documented duration.",),
        ),
        _metric(
            few,
            "errors",
            "Errors and refusals",
            0,
            "count",
            "phase8-specification",
            numerator=0,
            denominator=30,
        ),
        _metric(few, "api_cost_usd", "API cost", 0.0, "usd", "phase5-results"),
    )
    experiments.append(ExperimentDetail.model_validate(few))

    oracle30 = _base(
        "phase4-oracle-same30",
        "Oracle-formal symbolic ceiling — frozen same 30",
        "Phase 4",
        "Oracle AST same-30",
        status=ExperimentStatus.PASS,
        commit="eb319d661eca3ae1164407806a91c80eb2510a9e",
        branch="phase/04-symbolic-engine",
        source_ids=("symbolic-engine", "pilot-selection"),
        model=None,
        digest=None,
        run_id="phase4-same30-conformance",
        replay="DETERMINISTIC_RECOMPUTATION",
        provider_calls=0,
        limitations=("Consumes dataset-supplied oracle formal structures, not natural language.",),
        groups=("pilot-30-oracle", "pilot-30-selection"),
    )
    oracle30["metrics"] = (
        _metric(
            oracle30,
            "accuracy",
            "Accuracy",
            1.0,
            "ratio",
            "symbolic-engine",
            numerator=30,
            denominator=30,
        ),
        _metric(
            oracle30,
            "coverage",
            "Coverage",
            1.0,
            "ratio",
            "symbolic-engine",
            numerator=30,
            denominator=30,
        ),
        _metric(
            oracle30,
            "proof_verification_rate",
            "Proof verification rate",
            1.0,
            "ratio",
            "symbolic-engine",
            numerator=30,
            denominator=30,
        ),
        _metric(oracle30, "api_cost_usd", "API cost", 0.0, "usd", "symbolic-engine"),
    )
    experiments.append(ExperimentDetail.model_validate(oracle30))

    oracle300 = _base(
        "phase4-oracle-300",
        "Oracle-formal symbolic conformance — balanced 300",
        "Phase 4",
        "Oracle AST balanced-300",
        status=ExperimentStatus.PASS,
        commit="eb319d661eca3ae1164407806a91c80eb2510a9e",
        branch="phase/04-symbolic-engine",
        source_ids=("symbolic-engine",),
        sample_size=300,
        manifest=None,
        model=None,
        digest=None,
        run_id="phase4-balanced-conformance300",
        replay="DETERMINISTIC_RECOMPUTATION",
        provider_calls=0,
        limitations=("Oracle symbolic-engine result; not end-to-end natural-language evidence.",),
        groups=("oracle-300",),
        variant="OWA depth-5 balanced oracle-structure conformance",
    )
    oracle_metrics = [
        _metric(
            oracle300,
            "accuracy",
            "Accuracy",
            1.0,
            "ratio",
            "symbolic-engine",
            numerator=300,
            denominator=300,
        ),
        _metric(
            oracle300,
            "coverage",
            "Coverage",
            1.0,
            "ratio",
            "symbolic-engine",
            numerator=300,
            denominator=300,
        ),
        _metric(
            oracle300,
            "proof_verification_rate",
            "Proof verification rate",
            1.0,
            "ratio",
            "symbolic-engine",
            numerator=300,
            denominator=300,
        ),
    ]
    for depth in (0, 1, 2, 3, 5):
        oracle_metrics.append(
            _metric(
                oracle300,
                "accuracy",
                f"Accuracy at depth {depth}",
                1.0,
                "ratio",
                "symbolic-engine",
                numerator=60,
                denominator=60,
                evidence_type=EvidenceType.DERIVED,
                formula="20 examples x 3 labels, all correct",
                dimensions={"depth": str(depth)},
            )
        )
    for label in ("ENTAILED", "CONTRADICTED", "UNKNOWN"):
        oracle_metrics.append(
            _metric(
                oracle300,
                "accuracy",
                f"Accuracy for {label}",
                1.0,
                "ratio",
                "symbolic-engine",
                numerator=100,
                denominator=100,
                evidence_type=EvidenceType.DERIVED,
                formula="20 examples x 5 depths, all correct",
                dimensions={"label": label},
            )
        )
    oracle300["metrics"] = tuple(oracle_metrics)
    experiments.append(ExperimentDetail.model_validate(oracle300))

    phase5 = _base(
        "phase5-hybrid",
        "Neural parser plus deterministic symbolic engine",
        "Phase 5",
        "Parser + symbolic engine",
        status=ExperimentStatus.COMPLETE_WITH_NEGATIVE_RESULT,
        commit="bd9faaef321fb7e926c77d1678517eb9f65b555b",
        branch="phase/05-neural-semantic-parser",
        source_ids=("phase5-results", "pilot-selection"),
        run_id="phase5-frozen-pilot",
        replay="58_OF_58_ZERO_CALL_REPLAY_DOCUMENTED",
        provider_calls=57,
        limitations=("Semantic parsing is the observed bottleneck.", "Development-only sample."),
    )
    phase5["metrics"] = (
        _metric(
            phase5,
            "accuracy",
            "Accuracy",
            0.1,
            "ratio",
            "phase5-results",
            numerator=3,
            denominator=30,
        ),
        _metric(
            phase5,
            "coverage",
            "Coverage",
            4 / 30,
            "ratio",
            "phase5-results",
            numerator=4,
            denominator=30,
        ),
        _metric(
            phase5,
            "answered_only_accuracy",
            "Answered-only accuracy",
            0.75,
            "ratio",
            "phase5-results",
            numerator=3,
            denominator=4,
        ),
        _metric(
            phase5,
            "macro_f1",
            "Macro F1",
            0.1632,
            "ratio",
            "phase5-results",
            limitations=("Approximate documented value.",),
        ),
        _metric(
            phase5,
            "structured_pairs",
            "Complete structured pairs",
            29,
            "count",
            "phase5-results",
            numerator=29,
            denominator=30,
        ),
        _metric(
            phase5,
            "source_covered_pairs",
            "Source-covered pairs",
            19,
            "count",
            "phase5-results",
            numerator=19,
            denominator=29,
        ),
        _metric(
            phase5,
            "semantic_valid_pairs",
            "Semantically valid AST pairs",
            4,
            "count",
            "phase5-results",
            numerator=4,
            denominator=19,
        ),
        _metric(
            phase5,
            "accepted_records",
            "Accepted/answered records",
            4,
            "count",
            "phase5-results",
            numerator=4,
            denominator=30,
        ),
        _metric(
            phase5,
            "proof_verification_rate",
            "Proof verification rate",
            1.0,
            "ratio",
            "phase5-results",
            numerator=4,
            denominator=4,
        ),
        _metric(
            phase5, "errors", "Errors", 26, "count", "phase5-results", numerator=26, denominator=30
        ),
        _metric(
            phase5,
            "error_count",
            "Semantic invalid",
            15,
            "count",
            "phase5-results",
            dimensions={"error": "SEMANTIC_INVALID"},
        ),
        _metric(
            phase5,
            "error_count",
            "Source coverage error",
            10,
            "count",
            "phase5-results",
            dimensions={"error": "SOURCE_COVERAGE_ERROR"},
        ),
        _metric(
            phase5,
            "error_count",
            "Structured output error",
            1,
            "count",
            "phase5-results",
            dimensions={"error": "STRUCTURED_OUTPUT_ERROR"},
        ),
        _metric(
            phase5,
            "statement_precision",
            "Statement semantic precision",
            0.4189,
            "ratio",
            "phase5-results",
        ),
        _metric(
            phase5,
            "statement_recall",
            "Statement semantic recall",
            0.0625,
            "ratio",
            "phase5-results",
        ),
        _metric(phase5, "statement_f1", "Statement semantic F1", 0.1088, "ratio", "phase5-results"),
        _metric(
            phase5, "closure_precision", "Closure precision", 0.2742, "ratio", "phase5-results"
        ),
        _metric(phase5, "closure_recall", "Closure recall", 0.2394, "ratio", "phase5-results"),
        _metric(phase5, "closure_f1", "Closure F1", 0.2556, "ratio", "phase5-results"),
        _metric(phase5, "input_tokens", "Input tokens", 38397, "tokens", "phase5-results"),
        _metric(phase5, "output_tokens", "Output tokens", 28086, "tokens", "phase5-results"),
        _metric(
            phase5,
            "inference_seconds",
            "Provider duration",
            10903.746,
            "seconds",
            "phase5-results",
            evidence_type=EvidenceType.DERIVED,
            formula="10,903,746 ms / 1,000",
        ),
        _metric(phase5, "api_cost_usd", "API cost", 0.0, "usd", "phase5-results"),
    )
    experiments.append(ExperimentDetail.model_validate(phase5))

    for experiment_id, name, source_id, commit, branch, replay, limitation in (
        (
            "phase6-original-blocked",
            "Original Phase 6 interrupted attempt",
            "phase6-original",
            "4270c83e2d5618939de9120bde307df966ce6ae3",
            "phase/06-validation-correction-abstention",
            "BLOCKED_MISSING_IMMUTABLE_CACHE",
            "P1/P2 metrics are unavailable because frozen cache evidence was lost.",
        ),
        (
            "phase6-r2-blocked",
            "Phase 6-R2 recovery replication",
            "phase6-r2",
            "3c6106d21288ed31829bd6eeb5db96e7d9ee9705",
            "phase/06r2-recovery-replication",
            "BLOCKED_57_OF_58_COMPONENTS",
            "One frozen theory request failed structured output twice; no P0/P1/P2 predictions were sealed.",
        ),
    ):
        blocked = _base(
            experiment_id,
            name,
            "Phase 6-R2" if "r2" in experiment_id else "Phase 6",
            "Blocked correction attempt",
            status=ExperimentStatus.BLOCKED,
            commit=commit,
            branch=branch,
            source_ids=(source_id, "pilot-selection"),
            run_id=None,
            replay=replay,
            provider_calls=None,
            cost=0.0,
            limitations=(limitation,),
            groups=("phase6-history",),
            chart_eligible=False,
        )
        blocked["metrics"] = (
            _metric(
                blocked,
                "accuracy",
                "Accuracy",
                None,
                "ratio",
                source_id,
                evidence_type=EvidenceType.UNAVAILABLE,
                limitations=(limitation,),
            ),
            _metric(
                blocked,
                "coverage",
                "Coverage",
                None,
                "ratio",
                source_id,
                evidence_type=EvidenceType.UNAVAILABLE,
                limitations=(limitation,),
            ),
            _metric(
                blocked,
                "answered_only_accuracy",
                "Answered-only accuracy",
                None,
                "ratio",
                source_id,
                evidence_type=EvidenceType.UNAVAILABLE,
                limitations=(limitation,),
            ),
        )
        experiments.append(ExperimentDetail.model_validate(blocked))

    for policy, correct, answered, abstained, errors, macro_f1 in (
        ("P0_RAW", 2, 2, 0, 28, 0.1212),
        ("P1_CORRECTED", 0, 0, 22, 8, 0.0),
        ("P2_SELECTIVE", 0, 0, 22, 8, 0.0),
    ):
        slug = policy.split("_")[0].lower()
        r3 = _base(
            f"phase6-r3-{slug}",
            f"Phase 6-R3 {policy}",
            "Phase 6-R3",
            f"R3 {policy}",
            status=ExperimentStatus.COMPLETE_WITH_NEGATIVE_RESULT,
            commit="4a74aa56f4b03b4c639b3cf79c74e59ad1e2f7f0",
            branch="phase/06r3-terminal-failure",
            source_ids=("phase6-r3", "pilot-selection"),
            policy=policy,
            run_id="phase6-r3-live-resumed-3",
            replay="67_OF_67_ZERO_CALL_REPLAY",
            provider_calls=65,
            limitations=(
                "R3 uses regenerated physical model responses and is not paired with historical Phase 5.",
            ),
            groups=("phase6-r3-policies",),
        )
        r3_metrics: list[MetricEvidence] = [
            _metric(
                r3,
                "accuracy",
                "Accuracy",
                correct / 30,
                "ratio",
                "phase6-r3",
                numerator=correct,
                denominator=30,
            ),
            _metric(
                r3,
                "coverage",
                "Coverage",
                answered / 30,
                "ratio",
                "phase6-r3",
                numerator=answered,
                denominator=30,
            ),
            _metric(
                r3,
                "answered_only_accuracy",
                "Answered-only accuracy",
                correct / answered if answered else None,
                "ratio",
                "phase6-r3",
                numerator=correct if answered else None,
                denominator=answered if answered else None,
                evidence_type=EvidenceType.DOCUMENTED if answered else EvidenceType.UNAVAILABLE,
                limitations=() if answered else ("No answered records; denominator is zero.",),
            ),
            _metric(r3, "macro_f1", "Macro F1", macro_f1, "ratio", "phase6-r3"),
            _metric(
                r3,
                "answered",
                "Answered records",
                answered,
                "count",
                "phase6-r3",
                numerator=answered,
                denominator=30,
            ),
            _metric(
                r3,
                "abstained",
                "Abstained records",
                abstained,
                "count",
                "phase6-r3",
                numerator=abstained,
                denominator=30,
            ),
            _metric(
                r3,
                "errors",
                "Errors",
                errors,
                "count",
                "phase6-r3",
                numerator=errors,
                denominator=30,
            ),
            _metric(
                r3,
                "proof_verification_rate",
                "Proof verification rate",
                1.0 if answered else None,
                "ratio",
                "phase6-r3",
                numerator=answered if answered else None,
                denominator=answered if answered else None,
                evidence_type=EvidenceType.DOCUMENTED if answered else EvidenceType.UNAVAILABLE,
                limitations=() if answered else ("No proof attempts were produced.",),
            ),
            _metric(r3, "api_cost_usd", "API cost", 0.0, "usd", "phase6-r3"),
        ]
        if policy == "P0_RAW":
            for depth, depth_correct in ((0, 0), (1, 1), (2, 1), (3, 0), (5, 0)):
                r3_metrics.append(
                    _metric(
                        r3,
                        "accuracy",
                        f"Accuracy at depth {depth}",
                        depth_correct / 6,
                        "ratio",
                        "phase6-r3",
                        numerator=depth_correct,
                        denominator=6,
                        dimensions={"depth": str(depth)},
                    )
                )
            for label, label_correct in (("ENTAILED", 0), ("CONTRADICTED", 1), ("UNKNOWN", 1)):
                r3_metrics.append(
                    _metric(
                        r3,
                        "accuracy",
                        f"Accuracy for {label}",
                        label_correct / 10,
                        "ratio",
                        "phase6-r3",
                        numerator=label_correct,
                        denominator=10,
                        dimensions={"label": label},
                    )
                )
        r3["metrics"] = tuple(r3_metrics)
        experiments.append(ExperimentDetail.model_validate(r3))

    formal = _base(
        "phase7-formal-canaries",
        "Phase 7 deterministic formal canaries",
        "Phase 7",
        "Formal AST canaries",
        status=ExperimentStatus.PASS,
        commit=CHECKPOINT,
        branch="phase/07-end-to-end-integration",
        source_ids=("phase7-results", "phase7-manifest"),
        sample_size=4,
        split="synthetic",
        dataset="Synthetic formal fixtures",
        dataset_version="1.0",
        variant="ENTAILED, CONTRADICTED, UNKNOWN and INCONSISTENT",
        manifest="experiments/manifests/phase7-integration-canaries.v1.json",
        model=None,
        digest=None,
        run_id="phase7-formal-canaries",
        replay="CANONICAL_REPEAT_VERIFIED",
        provider_calls=0,
        groups=("phase7-synthetic",),
        chart_eligible=False,
        recorded_at=datetime(2026, 8, 9, tzinfo=UTC),
    )
    formal["metrics"] = (
        _metric(
            formal,
            "accuracy",
            "Expected formal outcomes",
            1.0,
            "ratio",
            "phase7-results",
            numerator=4,
            denominator=4,
        ),
        _metric(
            formal,
            "coverage",
            "Coverage",
            1.0,
            "ratio",
            "phase7-results",
            numerator=4,
            denominator=4,
        ),
        _metric(
            formal,
            "proof_verification_rate",
            "Proof verification rate",
            1.0,
            "ratio",
            "phase7-results",
            numerator=4,
            denominator=4,
        ),
        _metric(formal, "provider_calls", "Provider calls", 0, "count", "phase7-results"),
    )
    experiments.append(ExperimentDetail.model_validate(formal))

    natural = _base(
        "phase7-natural-canary",
        "Phase 7 local natural-language integration canary",
        "Phase 7",
        "Natural-language canary",
        status=ExperimentStatus.COMPLETE_WITH_NEGATIVE_RESULT,
        commit=CHECKPOINT,
        branch="phase/07-end-to-end-integration",
        source_ids=("phase7-results", "phase7-manifest"),
        sample_size=1,
        split="synthetic",
        dataset="Synthetic robin theory",
        dataset_version="1.0",
        variant="P2 integration canary",
        manifest="experiments/manifests/phase7-integration-canaries.v1.json",
        policy="P2_SELECTIVE",
        run_id="phase7-natural-robin-live",
        replay="4_HITS_ZERO_CALL_REPLAY",
        provider_calls=4,
        limitations=(
            "Integration canary, not a benchmark record.",
            "Observed UNKNOWN was a semantic-parser correctness miss.",
        ),
        groups=("phase7-synthetic",),
        chart_eligible=False,
        recorded_at=datetime(2026, 8, 9, tzinfo=UTC),
    )
    natural["metrics"] = (
        _metric(
            natural,
            "accuracy",
            "Canary correctness",
            0.0,
            "ratio",
            "phase7-results",
            numerator=0,
            denominator=1,
        ),
        _metric(
            natural,
            "coverage",
            "Coverage",
            1.0,
            "ratio",
            "phase7-results",
            numerator=1,
            denominator=1,
        ),
        _metric(
            natural,
            "proof_verification_rate",
            "Proof verification rate",
            1.0,
            "ratio",
            "phase7-results",
            numerator=1,
            denominator=1,
        ),
        _metric(natural, "provider_calls", "Local dispatches", 4, "count", "phase7-results"),
        _metric(
            natural, "correction_attempts", "Correction attempts", 0, "count", "phase7-results"
        ),
    )
    experiments.append(ExperimentDetail.model_validate(natural))

    comparisons = (
        ComparisonCompatibility(
            comparison_id="direct-vs-few-shot",
            title="Direct versus fixed few-shot local LLM",
            comparison_type=ComparisonType.PAIRED,
            experiment_ids=("phase3-direct", "phase3-few-shot"),
            paired=True,
            same_selection=True,
            supported_metrics=(
                "accuracy",
                "coverage",
                "macro_f1",
                "input_tokens",
                "output_tokens",
                "inference_seconds",
            ),
            outcome_counts={
                "both_correct": 13,
                "direct_only_correct": 4,
                "few_shot_only_correct": 2,
                "both_incorrect": 11,
            },
            warning="Paired on the same frozen 30-example development manifest; the pilot is too small for superiority claims.",
            evidence_sources=("phase5-results", "phase8-specification", "pilot-selection"),
        ),
        ComparisonCompatibility(
            comparison_id="baselines-vs-phase5",
            title="LLM baselines versus Phase 5 hybrid",
            comparison_type=ComparisonType.DESCRIPTIVE_ONLY,
            experiment_ids=("phase3-direct", "phase3-few-shot", "phase5-hybrid"),
            paired=False,
            same_selection=True,
            supported_metrics=("accuracy", "coverage", "macro_f1"),
            warning="Same frozen selection, but conditions use different inference architectures; report descriptively without causal attribution.",
            evidence_sources=("phase5-results", "pilot-selection"),
        ),
        ComparisonCompatibility(
            comparison_id="phase5-vs-oracle",
            title="Phase 5 natural-language pipeline versus oracle symbolic ceiling",
            comparison_type=ComparisonType.SAME_SELECTION_DIFFERENT_REPRESENTATION,
            experiment_ids=("phase5-hybrid", "phase4-oracle-same30"),
            paired=False,
            same_selection=True,
            supported_metrics=("accuracy", "coverage", "proof_verification_rate"),
            warning="The oracle consumes supplied formal structures and is not a natural-language system.",
            evidence_sources=("phase5-results", "symbolic-engine", "pilot-selection"),
        ),
        ComparisonCompatibility(
            comparison_id="phase5-vs-r3",
            title="Historical Phase 5 versus Phase 6-R3",
            comparison_type=ComparisonType.INCOMPARABLE,
            experiment_ids=("phase5-hybrid", "phase6-r3-p0", "phase6-r3-p1", "phase6-r3-p2"),
            paired=False,
            same_selection=True,
            supported_metrics=("accuracy", "coverage"),
            warning="The original Phase 5 cache was lost; R3 used separately regenerated physical responses and is not a controlled paired correction ablation.",
            evidence_sources=("phase5-results", "phase6-r3", "pilot-selection"),
        ),
        ComparisonCompatibility(
            comparison_id="phase6-r3-policies",
            title="Phase 6-R3 policy dispositions",
            comparison_type=ComparisonType.DESCRIPTIVE_ONLY,
            experiment_ids=("phase6-r3-p0", "phase6-r3-p1", "phase6-r3-p2"),
            paired=False,
            same_selection=True,
            supported_metrics=("accuracy", "coverage", "answered", "abstained", "errors"),
            warning="P0/P1/P2 share the R3 selection; zero answered records make P1/P2 answered-only accuracy unavailable.",
            evidence_sources=("phase6-r3", "pilot-selection"),
        ),
    )

    return ResearchCatalogue(
        source_checkpoint=CHECKPOINT,
        evidence_sources=tuple(SOURCES.values()),
        experiments=tuple(experiments),
        comparisons=comparisons,
        global_limitations=(
            "All benchmark metrics are development-only; no ProofWriter test-split record is included.",
            "The 30-example pilots do not support state-of-the-art, generalisation or statistical-superiority claims.",
            "Oracle formal-structure results are not end-to-end natural-language results.",
            "Phase 5 and Phase 6-R3 are not a paired correction ablation because the original cache was lost.",
            "ProofWriter's dataset licence remains unverified.",
            "Unavailable values remain null and are never interpreted as zero.",
        ),
    )
