// Generated by `python -m verilogic_ns_api.orchestration export-schemas`.
// Do not edit by hand.

export const INPUT_MODES = ["NATURAL_LANGUAGE", "FORMAL_AST"] as const;
export const POLICY_MODES = ["P0_RAW", "P1_CORRECTED", "P2_SELECTIVE"] as const;
export const RUN_STATUSES = ["QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCEL_REQUESTED", "CANCELLED"] as const;
export const PIPELINE_DISPOSITIONS = ["ANSWERED", "ABSTAINED", "ERROR"] as const;
export const LOGICAL_RESULTS = ["ENTAILED", "CONTRADICTED", "UNKNOWN", "INCONSISTENT"] as const;
export const STAGE_NAMES = ["INPUT_VALIDATION", "THEORY_PARSING", "QUERY_PARSING", "SOURCE_COVERAGE", "SEMANTIC_VALIDATION", "CRITIC", "CORRECTION", "RELIABILITY_POLICY", "SYMBOLIC_REASONING", "PROOF_VERIFICATION", "FINAL_DECISION"] as const;
export const STAGE_STATUSES = ["NOT_STARTED", "RUNNING", "SUCCEEDED", "SKIPPED", "ABSTAINED", "FAILED"] as const;

export type InputMode = (typeof INPUT_MODES)[number];
export type PolicyMode = (typeof POLICY_MODES)[number];
export type RunStatus = (typeof RUN_STATUSES)[number];
export type PipelineDisposition = (typeof PIPELINE_DISPOSITIONS)[number];
export type LogicalResult = (typeof LOGICAL_RESULTS)[number];
export type StageName = (typeof STAGE_NAMES)[number];
export type StageStatus = (typeof STAGE_STATUSES)[number];

export interface NaturalLanguageStatement {
  source_id?: string | null;
  kind: "fact" | "rule";
  text: string;
}

export interface PipelineRequest {
  schema_version: "1.0";
  input_mode: InputMode;
  policy_mode: PolicyMode;
  natural_language?: { statements: NaturalLanguageStatement[]; query: string } | null;
  formal_ast?: { theory: Record<string, unknown>; query: Record<string, unknown> } | null;
}

export interface StageTrace {
  stage: StageName;
  status: StageStatus;
  duration_ms: number;
  cache_status: "hit" | "miss" | "mixed" | "not_applicable";
  error_code?: string | null;
  message?: string | null;
}

export interface ExplanationStep {
  sequence: number;
  kind: "fact" | "rule";
  statement: string;
  source_id: string;
  source_text: string;
  depth: number;
  node_id: string;
}

export interface PipelineResult {
  schema_version: "1.0";
  disposition: PipelineDisposition;
  logical_result?: LogicalResult | null;
  explanation: {
    schema_version: "1.0";
    headline: string;
    summary: string;
    steps: ExplanationStep[];
    support_root_id?: string | null;
    opposition_root_id?: string | null;
    proof_depth?: number | null;
    proof_hash?: string | null;
    verifier_status: "VERIFIED" | "NOT_APPLICABLE";
    reasons: string[];
  };
  trace: StageTrace[];
  provenance: Record<string, unknown>;
  proof?: Record<string, unknown> | null;
  proof_verification?: Record<string, unknown> | null;
  reasoning_telemetry?: Record<string, unknown> | null;
  accepted_theory?: Record<string, unknown> | null;
  correction_attempted: boolean;
  abstention_reason?: string | null;
  error?: { stage: StageName; code: string; message: string } | null;
}

export interface PipelineRunAccepted {
  schema_version: "1.0";
  run_id: string;
  status: "QUEUED" | "RUNNING";
}

export interface PipelineRunState {
  schema_version: "1.0";
  run_id: string;
  status: RunStatus;
  current_stage?: StageName | null;
  submitted_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  result?: PipelineResult | null;
}

export interface CapabilitiesResponse {
  schema_version: "1.0";
  api_version: "v1";
  supported_input_modes: InputMode[];
  supported_policy_modes: PolicyMode[];
  symbolic_engine_ready: boolean;
  local_model_ready: boolean;
  provider_mode: "live" | "cache_only";
  model_name: string;
  model_digest: string;
  provider_version: string;
  maximum_active_jobs: 1;
  maximum_queued_jobs: number;
  resource_limits: Record<string, number | null>;
  schema_hashes: Record<string, string>;
}

export const CONTRACT_SCHEMA_HASHES = {
  "neurosymbolic-api-error": "ae0c057ad85d0fe54cd54c63e6e248def504ae8f57acbb0b52706f900c77d233",
  "neurosymbolic-capabilities": "e90c9943ece2c22388f58e112af27235df663f5c799573f1d71cbb295eb898bf",
  "neurosymbolic-pipeline-result": "216bb4b8d6733741d21529959576cc9efe04719679068fd1fa031b2726dfe045",
  "neurosymbolic-run-accepted": "94930cf334b2406ffcfca11f5a63aeafc9f501d3e8651303f65f9447b507cc46",
  "neurosymbolic-run-request": "e2e7ec9b066e40c24c1ced3e43f032e52cdbd1d289f42f82c4465fb9a03c6e71",
  "neurosymbolic-run-state": "3f697fe4fab0dbfb08e36cc74d9c186e9cc11dfe46261305e580fd8767193199"
} as const;
