// Generated by `python -m verilogic_ns_api.research_frontend export-schemas`.
// Do not edit by hand.

export const EXPERIMENT_STATUSES = ["PASS", "BLOCKED", "INVALIDATED", "COMPLETE_WITH_NEGATIVE_RESULT"] as const;
export const COMPARISON_TYPES = ["PAIRED", "SAME_SELECTION_DIFFERENT_REPRESENTATION", "DESCRIPTIVE_ONLY", "INCOMPARABLE"] as const;
export const EVIDENCE_TYPES = ["DIRECTLY_OBSERVED", "DERIVED", "DOCUMENTED", "UNAVAILABLE"] as const;
export type ExperimentStatus = (typeof EXPERIMENT_STATUSES)[number];
export type ComparisonType = (typeof COMPARISON_TYPES)[number];
export type EvidenceType = (typeof EVIDENCE_TYPES)[number];

export interface MetricEvidence {
  metric_id: string; display_name: string; value: number | null; unit: string;
  numerator: number | null; denominator: number | null; sample_size: number;
  dataset: string; dataset_version: string; split: string; benchmark_variant: string;
  selection_manifest: string | null; phase: string; condition: string; policy_mode: string | null;
  model_name: string | null; model_digest: string | null; run_id: string | null;
  evidence_type: EvidenceType; source_artifact: string; source_artifact_hash: string;
  source_commit: string | null; derivation_formula: string | null; comparability_group: string;
  limitations: string[]; verification_status: string; dimensions: Record<string, string>;
}
export interface ExperimentSummary {
  experiment_id: string; name: string; phase: string; condition: string;
  policy_mode: string | null; status: ExperimentStatus; recorded_at: string | null;
  commit: string | null; model_name: string | null; dataset: string; split: string;
  sample_size: number; replay_status: string; provider_call_count: number | null;
  api_cost_usd: number | null; primary_metrics: Record<string, number | null>;
  main_limitation: string | null; comparability_groups: string[]; chart_eligible: boolean;
  evidence_verification_status: string;
}
export interface CatalogueOverview {
  schema_version: "1.0"; catalogue_id: string; catalogue_version: string;
  catalogue_hash: string; evidence_validation_status: "VERIFIED";
  experiment_count: number; comparison_count: number; experiments: ExperimentSummary[];
  global_limitations: string[]; zero_cost: boolean; provider_calls_during_phase8: number;
  local_provider_calls_during_phase9: number; hosted_provider_calls_during_phase9: number;
  api_cost_usd_during_phase9: number;
}
export interface ExperimentDetail extends Omit<ExperimentSummary, "primary_metrics" | "main_limitation"> {
  branch: string | null; model_digest: string | null; dataset_version: string;
  benchmark_variant: string; selection_manifest: string | null; run_id: string | null;
  metrics: MetricEvidence[]; evidence_sources: string[]; limitations: string[];
}
export interface ComparisonCompatibility {
  comparison_id: string; title: string; comparison_type: ComparisonType;
  experiment_ids: string[]; paired: boolean; same_selection: boolean;
  supported_metrics: string[]; outcome_counts: Record<string, number | null>;
  warning: string; evidence_sources: string[]; limitations: string[];
}
export interface ExperimentListResponse {
  schema_version: "1.0"; items: ExperimentSummary[]; total: number; page: number; page_size: number;
}
export interface AstLiteral {
  canonical_id: string; predicate: string; arguments: Array<{kind: "entity" | "variable"; value: string}>;
  negated: boolean; source_id: string; display: string;
}
export interface AstRule {
  rule_id: string; variables: string[]; premises: AstLiteral[]; conclusion: AstLiteral; source_id: string;
}
export interface AstSourceMapping {
  source_id: string; text: string; referenced_by: string[];
}
export interface NormalizedAstInspection {
  schema_version: "1.0"; theory_id: string; canonical_theory_id: string;
  facts: AstLiteral[]; rules: AstRule[]; query: AstLiteral;
  predicates: Array<{name: string; arity: 1 | 2; argument_types: string[] | null}>;
  entities: Array<Record<string, string | null>>; source_mapping: AstSourceMapping[];
  semantic_validation_status: "VALID"; source_coverage_status: "COMPLETE" | "INCOMPLETE";
  correction_attempted: boolean; correction_diff: Record<string, unknown>;
  proof_roots: string[]; canonical_json: Record<string, unknown>;
}
export const RESEARCH_SCHEMA_HASHES = {
  "research-aggregate-export-manifest": "6eec4bb55d55ca8e839ce586698fe5a1c2645d91467ceaffe4850eafac9393d8",
  "research-api-error": "fbe25aed4fba1a5d2b1d01bc22ccde8b18d663207c3daec8575a5e2713fc15c5",
  "research-catalogue": "d93434e0ae29a3522f85f5355fcc65c9171bbc74615927300d1391709408b851",
  "research-comparison-compatibility": "46e5a4149c754e27e17a82e3ddec3c425b328ae0f8d7991b18e72e6707a232dc",
  "research-experiment-detail": "1005529d70e6aec24cd89b124f868aa007cac178239ac34b79bca32535a5b38f",
  "research-experiment-summary": "d639073e2949126e3e08d736a3c84811901394c1d4952b5af710e4c24f4fc496",
  "research-metric-evidence": "9a3c88d30b25d2edb717eb051b568e8acbf3e5028d07a2d230e4f0e980d09656",
  "research-normalized-ast-inspection": "ac7dfeaced4f41d27d0daa56836940848855f5c615191d45bacd39bc19faefc8"
} as const;
